In [547]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib as plt

In [548]:
movie = pd.set_option('display.max_rows',None)
movie = pd.set_option('display.max_columns',None)

In [549]:
credit = pd.read_csv("tmdb_5000_credits.csv")
movie = pd.read_csv("tmdb_5000_movies.csv")

In [550]:
credit.head(1)

,movie_id,title,cast,crew
0,19995,Avatar,"[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."

In [551]:
movie.head(1)

,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,production_companies,production_countries,release_date,revenue,runtime,spoken_languages,status,tagline,title,vote_average,vote_count
0,237000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.avatarmovie.com/,19995,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...",en,Avatar,"In the 22nd century, a paraplegic Marine is di...",150.437577,"[{""name"": ""Ingenious Film Partners"", ""id"": 289...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2009-12-10,2787965087,162.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Enter the World of Pandora.,Avatar,7.2,11800

In [552]:
print("credit",credit.shape)
print("movie",movie.shape)

credit (4803, 4)
movie (4803, 20)

In [553]:
movie = pd.merge(movie, credit, on="title")
movie.shape

(4809, 23)

In [554]:
movie.head(1)

,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,production_companies,production_countries,release_date,revenue,runtime,spoken_languages,status,tagline,title,vote_average,vote_count,movie_id,cast,crew
0,237000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.avatarmovie.com/,19995,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...",en,Avatar,"In the 22nd century, a paraplegic Marine is di...",150.437577,"[{""name"": ""Ingenious Film Partners"", ""id"": 289...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2009-12-10,2787965087,162.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Enter the World of Pandora.,Avatar,7.2,11800,19995,"[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."

In [555]:
movie.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4809 entries, 0 to 4808
Data columns (total 23 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   budget                4809 non-null   int64
 1   genres                4809 non-null   object
 2   homepage              1713 non-null   object
 3   id                    4809 non-null   int64
 4   keywords              4809 non-null   object
 5   original_language     4809 non-null   object
 6   original_title        4809 non-null   object
 7   overview              4806 non-null   object
 8   popularity            4809 non-null   float64
 9   production_companies  4809 non-null   object
 10  production_countries  4809 non-null   object
 11  release_date          4808 non-null   object
 12  revenue               4809 non-null   int64
 13  runtime               4807 non-null   float64
 14  spoken_languages      4809 non-null   object
 15  status                4809 non-null   object
 16  tagline               3965 non-null   object
 17  title                 4809 non-null   object
 18  vote_average          4809 non-null   float64
 19  vote_count            4809 non-null   int64
 20  movie_id              4809 non-null   int64
 21  cast                  4809 non-null   object
 22  crew                  4809 non-null   object
dtypes: float64(3), int64(5), object(15)
memory usage: 864.2+ KB

In [556]:
movie = movie[["movie_id","title", "overview", "genres", "keywords", "cast", "crew"]]
movie.head(1)

,movie_id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di...","[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...","[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."

In [557]:
movie.shape

(4809, 7)

In [558]:
movie.isnull().sum()

movie_id    0
title       0
overview    3
genres      0
keywords    0
cast        0
crew        0
dtype: int64

In [559]:
movie.dropna(inplace=True)
movie.shape

(4806, 7)

In [560]:
movie.duplicated().sum()

0

# formate impruvment

In [561]:
print(type(movie["overview"][0]))
movie["overview"][0]

<class 'str'>

'In the 22nd century, a paraplegic Marine is dispatched to the moon Pandora on a unique mission, but becomes torn between following orders and protecting an alien civilization.'

In [562]:
# change in list movie["overview"]
movie["overview"] = movie["overview"].apply(lambda x: x.split())
movie.head(1)

,movie_id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"[In, the, 22nd, century,, a, paraplegic, Marin...","[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...","[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."

In [563]:
movie["genres"][0]

'[{"id": 28, "name": "Action"}, {"id": 12, "name": "Adventure"}, {"id": 14, "name": "Fantasy"}, {"id": 878, "name": "Science Fiction"}]'

In [564]:
def convert1(obj):  
    l = []
    for i in ast.literal_eval(obj):
        l.append(i["name"])
    return l

# for keywords
#  for keywords  convert(movie["genres"])  // # in this way we get error
movie["genres"] = movie["genres"].apply(convert1)

# for keywords
movie["keywords"] = movie["keywords"].apply(convert1)

movie.head(1)

,movie_id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"[In, the, 22nd, century,, a, paraplegic, Marin...","[Action, Adventure, Fantasy, Science Fiction]","[culture clash, future, space war, space colon...","[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."

In [565]:
# we need to all of column from first 3 dictionary element of "character"
movie["cast"][0]

'[{"cast_id": 242, "character": "Jake Sully", "credit_id": "5602a8a7c3a3685532001c9a", "gender": 2, "id": 65731, "name": "Sam Worthington", "order": 0}, {"cast_id": 3, "character": "Neytiri", "credit_id": "52fe48009251416c750ac9cb", "gender": 1, "id": 8691, "name": "Zoe Saldana", "order": 1}, {"cast_id": 25, "character": "Dr. Grace Augustine", "credit_id": "52fe48009251416c750aca39", "gender": 1, "id": 10205, "name": "Sigourney Weaver", "order": 2}, {"cast_id": 4, "character": "Col. Quaritch", "credit_id": "52fe48009251416c750ac9cf", "gender": 2, "id": 32747, "name": "Stephen Lang", "order": 3}, {"cast_id": 5, "character": "Trudy Chacon", "credit_id": "52fe48009251416c750ac9d3", "gender": 1, "id": 17647, "name": "Michelle Rodriguez", "order": 4}, {"cast_id": 8, "character": "Selfridge", "credit_id": "52fe48009251416c750ac9e1", "gender": 2, "id": 1771, "name": "Giovanni Ribisi", "order": 5}, {"cast_id": 7, "character": "Norm Spellman", "credit_id": "52fe48009251416c750ac9dd", "gender": 2, "id": 59231, "name": "Joel David Moore", "order": 6}, {"cast_id": 9, "character": "Moat", "credit_id": "52fe48009251416c750ac9e5", "gender": 1, "id": 30485, "name": "CCH Pounder", "order": 7}, {"cast_id": 11, "character": "Eytukan", "credit_id": "52fe48009251416c750ac9ed", "gender": 2, "id": 15853, "name": "Wes Studi", "order": 8}, {"cast_id": 10, "character": "Tsu\'Tey", "credit_id": "52fe48009251416c750ac9e9", "gender": 2, "id": 10964, "name": "Laz Alonso", "order": 9}, {"cast_id": 12, "character": "Dr. Max Patel", "credit_id": "52fe48009251416c750ac9f1", "gender": 2, "id": 95697, "name": "Dileep Rao", "order": 10}, {"cast_id": 13, "character": "Lyle Wainfleet", "credit_id": "52fe48009251416c750ac9f5", "gender": 2, "id": 98215, "name": "Matt Gerald", "order": 11}, {"cast_id": 32, "character": "Private Fike", "credit_id": "52fe48009251416c750aca5b", "gender": 2, "id": 154153, "name": "Sean Anthony Moran", "order": 12}, {"cast_id": 33, "character": "Cryo Vault Med Tech", "credit_id": "52fe48009251416c750aca5f", "gender": 2, "id": 397312, "name": "Jason Whyte", "order": 13}, {"cast_id": 34, "character": "Venture Star Crew Chief", "credit_id": "52fe48009251416c750aca63", "gender": 2, "id": 42317, "name": "Scott Lawrence", "order": 14}, {"cast_id": 35, "character": "Lock Up Trooper", "credit_id": "52fe48009251416c750aca67", "gender": 2, "id": 986734, "name": "Kelly Kilgour", "order": 15}, {"cast_id": 36, "character": "Shuttle Pilot", "credit_id": "52fe48009251416c750aca6b", "gender": 0, "id": 1207227, "name": "James Patrick Pitt", "order": 16}, {"cast_id": 37, "character": "Shuttle Co-Pilot", "credit_id": "52fe48009251416c750aca6f", "gender": 0, "id": 1180936, "name": "Sean Patrick Murphy", "order": 17}, {"cast_id": 38, "character": "Shuttle Crew Chief", "credit_id": "52fe48009251416c750aca73", "gender": 2, "id": 1019578, "name": "Peter Dillon", "order": 18}, {"cast_id": 39, "character": "Tractor Operator / Troupe", "credit_id": "52fe48009251416c750aca77", "gender": 0, "id": 91443, "name": "Kevin Dorman", "order": 19}, {"cast_id": 40, "character": "Dragon Gunship Pilot", "credit_id": "52fe48009251416c750aca7b", "gender": 2, "id": 173391, "name": "Kelson Henderson", "order": 20}, {"cast_id": 41, "character": "Dragon Gunship Gunner", "credit_id": "52fe48009251416c750aca7f", "gender": 0, "id": 1207236, "name": "David Van Horn", "order": 21}, {"cast_id": 42, "character": "Dragon Gunship Navigator", "credit_id": "52fe48009251416c750aca83", "gender": 0, "id": 215913, "name": "Jacob Tomuri", "order": 22}, {"cast_id": 43, "character": "Suit #1", "credit_id": "52fe48009251416c750aca87", "gender": 0, "id": 143206, "name": "Michael Blain-Rozgay", "order": 23}, {"cast_id": 44, "character": "Suit #2", "credit_id": "52fe48009251416c750aca8b", "gender": 2, "id": 169676, "name": "Jon Curry", "order": 24}, {"cast_id": 46, "character": "Ambient Room Tech", "credit_id": "52fe48009251416c750aca8f", "gender": 0, "id": 1048610, "name": "Luke Hawker", "order": 25}, {"cast_id": 47, "character": "Ambient Room Tech / Troupe", "credit_id": "52fe48009251416c750aca93", "gender": 0, "id": 42288, "name": "Woody Schultz", "order": 26}, {"cast_id": 48, "character": "Horse Clan Leader", "credit_id": "52fe48009251416c750aca97", "gender": 2, "id": 68278, "name": "Peter Mensah", "order": 27}, {"cast_id": 49, "character": "Link Room Tech", "credit_id": "52fe48009251416c750aca9b", "gender": 0, "id": 1207247, "name": "Sonia Yee", "order": 28}, {"cast_id": 50, "character": "Basketball Avatar / Troupe", "credit_id": "52fe48009251416c750aca9f", "gender": 1, "id": 1207248, "name": "Jahnel Curfman", "order": 29}, {"cast_id": 51, "character": "Basketball Avatar", "credit_id": "52fe48009251416c750acaa3", "gender": 0, "id": 89714, "name": "Ilram Choi", "order": 30}, {"cast_id": 52, "character": "Na\'vi Child", "credit_id": "52fe48009251416c750acaa7", "gender": 0, "id": 1207249, "name": "Kyla Warren", "order": 31}, {"cast_id": 53, "character": "Troupe", "credit_id": "52fe48009251416c750acaab", "gender": 0, "id": 1207250, "name": "Lisa Roumain", "order": 32}, {"cast_id": 54, "character": "Troupe", "credit_id": "52fe48009251416c750acaaf", "gender": 1, "id": 83105, "name": "Debra Wilson", "order": 33}, {"cast_id": 57, "character": "Troupe", "credit_id": "52fe48009251416c750acabb", "gender": 0, "id": 1207253, "name": "Chris Mala", "order": 34}, {"cast_id": 55, "character": "Troupe", "credit_id": "52fe48009251416c750acab3", "gender": 0, "id": 1207251, "name": "Taylor Kibby", "order": 35}, {"cast_id": 56, "character": "Troupe", "credit_id": "52fe48009251416c750acab7", "gender": 0, "id": 1207252, "name": "Jodie Landau", "order": 36}, {"cast_id": 58, "character": "Troupe", "credit_id": "52fe48009251416c750acabf", "gender": 0, "id": 1207254, "name": "Julie Lamm", "order": 37}, {"cast_id": 59, "character": "Troupe", "credit_id": "52fe48009251416c750acac3", "gender": 0, "id": 1207257, "name": "Cullen B. Madden", "order": 38}, {"cast_id": 60, "character": "Troupe", "credit_id": "52fe48009251416c750acac7", "gender": 0, "id": 1207259, "name": "Joseph Brady Madden", "order": 39}, {"cast_id": 61, "character": "Troupe", "credit_id": "52fe48009251416c750acacb", "gender": 0, "id": 1207262, "name": "Frankie Torres", "order": 40}, {"cast_id": 62, "character": "Troupe", "credit_id": "52fe48009251416c750acacf", "gender": 1, "id": 1158600, "name": "Austin Wilson", "order": 41}, {"cast_id": 63, "character": "Troupe", "credit_id": "52fe48019251416c750acad3", "gender": 1, "id": 983705, "name": "Sara Wilson", "order": 42}, {"cast_id": 64, "character": "Troupe", "credit_id": "52fe48019251416c750acad7", "gender": 0, "id": 1207263, "name": "Tamica Washington-Miller", "order": 43}, {"cast_id": 65, "character": "Op Center Staff", "credit_id": "52fe48019251416c750acadb", "gender": 1, "id": 1145098, "name": "Lucy Briant", "order": 44}, {"cast_id": 66, "character": "Op Center Staff", "credit_id": "52fe48019251416c750acadf", "gender": 2, "id": 33305, "name": "Nathan Meister", "order": 45}, {"cast_id": 67, "character": "Op Center Staff", "credit_id": "52fe48019251416c750acae3", "gender": 0, "id": 1207264, "name": "Gerry Blair", "order": 46}, {"cast_id": 68, "character": "Op Center Staff", "credit_id": "52fe48019251416c750acae7", "gender": 2, "id": 33311, "name": "Matthew Chamberlain", "order": 47}, {"cast_id": 69, "character": "Op Center Staff", "credit_id": "52fe48019251416c750acaeb", "gender": 0, "id": 1207265, "name": "Paul Yates", "order": 48}, {"cast_id": 70, "character": "Op Center Duty Officer", "credit_id": "52fe48019251416c750acaef", "gender": 0, "id": 1207266, "name": "Wray Wilson", "order": 49}, {"cast_id": 71, "character": "Op Center Staff", "credit_id": "52fe48019251416c750acaf3", "gender": 2, "id": 54492, "name": "James Gaylyn", "order": 50}, {"cast_id": 72, "character": "Dancer", "credit_id": "52fe48019251416c750acaf7", "gender": 0, "id": 1207267, "name": "Melvin Leno Clark III", "order": 51}, {"cast_id": 73, "character": "Dancer", "credit_id": "52fe48019251416c750acafb", "gender": 0, "id": 1207268, "name": "Carvon Futrell", "order": 52}, {"cast_id": 74, "character": "Dancer", "credit_id": "52fe48019251416c750acaff", "gender": 0, "id": 1207269, "name": "Brandon Jelkes", "order": 53}, {"cast_id": 75, "character": "Dancer", "credit_id": "52fe48019251416c750acb03", "gender": 0, "id": 1207270, "name": "Micah Moch", "order": 54}, {"cast_id": 76, "character": "Dancer", "credit_id": "52fe48019251416c750acb07", "gender": 0, "id": 1207271, "name": "Hanniyah Muhammad", "order": 55}, {"cast_id": 77, "character": "Dancer", "credit_id": "52fe48019251416c750acb0b", "gender": 0, "id": 1207272, "name": "Christopher Nolen", "order": 56}, {"cast_id": 78, "character": "Dancer", "credit_id": "52fe48019251416c750acb0f", "gender": 0, "id": 1207273, "name": "Christa Oliver", "order": 57}, {"cast_id": 79, "character": "Dancer", "credit_id": "52fe48019251416c750acb13", "gender": 0, "id": 1207274, "name": "April Marie Thomas", "order": 58}, {"cast_id": 80, "character": "Dancer", "credit_id": "52fe48019251416c750acb17", "gender": 0, "id": 1207275, "name": "Bravita A. Threatt", "order": 59}, {"cast_id": 81, "character": "Mining Chief (uncredited)", "credit_id": "52fe48019251416c750acb1b", "gender": 0, "id": 1207276, "name": "Colin Bleasdale", "order": 60}, {"cast_id": 82, "character": "Veteran Miner (uncredited)", "credit_id": "52fe48019251416c750acb1f", "gender": 0, "id": 107969, "name": "Mike Bodnar", "order": 61}, {"cast_id": 83, "character": "Richard (uncredited)", "credit_id": "52fe48019251416c750acb23", "gender": 0, "id": 1207278, "name": "Matt Clayton", "order": 62}, {"cast_id": 84, "character": "Nav\'i (uncredited)", "credit_id": "52fe48019251416c750acb27", "gender": 1, "id": 147898, "name": "Nicole Dionne", "order": 63}, {"cast_id": 85, "character": "Trooper (uncredited)", "credit_id": "52fe48019251416c750acb2b", "gender": 0, "id": 1207280, "name": "Jamie Harrison", "order": 64}, {"cast_id": 86, "character": "Trooper (uncredited)", "credit_id": "52fe48019251416c750acb2f", "gender": 0, "id": 1207281, "name": "Allan Henry", "order": 65}, {"cast_id": 87, "character": "Ground Technician (uncredited)", "credit_id": "52fe48019251416c750acb33", "gender": 2, "id": 1207282, "name": "Anthony Ingruber", "order": 66}, {"cast_id": 88, "character": "Flight Crew Mechanic (uncredited)", "credit_id": "52fe48019251416c750acb37", "gender": 0, "id": 1207283, "name": "Ashley Jeffery", "order": 67}, {"cast_id": 14, "character": "Samson Pilot", "credit_id": "52fe48009251416c750ac9f9", "gender": 0, "id": 98216, "name": "Dean Knowsley", "order": 68}, {"cast_id": 89, "character": "Trooper (uncredited)", "credit_id": "52fe48019251416c750acb3b", "gender": 0, "id": 1201399, "name": "Joseph Mika-Hunt", "order": 69}, {"cast_id": 90, "character": "Banshee (uncredited)", "credit_id": "52fe48019251416c750acb3f", "gender": 0, "id": 236696, "name": "Terry Notary", "order": 70}, {"cast_id": 91, "character": "Soldier (uncredited)", "credit_id": "52fe48019251416c750acb43", "gender": 0, "id": 1207287, "name": "Kai Pantano", "order": 71}, {"cast_id": 92, "character": "Blast Technician (uncredited)", "credit_id": "52fe48019251416c750acb47", "gender": 0, "id": 1207288, "name": "Logan Pithyou", "order": 72}, {"cast_id": 93, "character": "Vindum Raah (uncredited)", "credit_id": "52fe48019251416c750acb4b", "gender": 0, "id": 1207289, "name": "Stuart Pollock", "order": 73}, {"cast_id": 94, "character": "Hero (uncredited)", "credit_id": "52fe48019251416c750acb4f", "gender": 0, "id": 584868, "name": "Raja", "order": 74}, {"cast_id": 95, "character": "Ops Centreworker (uncredited)", "credit_id": "52fe48019251416c750acb53", "gender": 0, "id": 1207290, "name": "Gareth Ruck", "order": 75}, {"cast_id": 96, "character": "Engineer (uncredited)", "credit_id": "52fe48019251416c750acb57", "gender": 0, "id": 1062463, "name": "Rhian Sheehan", "order": 76}, {"cast_id": 97, "character": "Col. Quaritch\'s Mech Suit (uncredited)", "credit_id": "52fe48019251416c750acb5b", "gender": 0, "id": 60656, "name": "T. J. Storm", "order": 77}, {"cast_id": 98, "character": "Female Marine (uncredited)", "credit_id": "52fe48019251416c750acb5f", "gender": 0, "id": 1207291, "name": "Jodie Taylor", "order": 78}, {"cast_id": 99, "character": "Ikran Clan Leader (uncredited)", "credit_id": "52fe48019251416c750acb63", "gender": 1, "id": 1186027, "name": "Alicia Vela-Bailey", "order": 79}, {"cast_id": 100, "character": "Geologist (uncredited)", "credit_id": "52fe48019251416c750acb67", "gender": 0, "id": 1207292, "name": "Richard Whiteside", "order": 80}, {"cast_id": 101, "character": "Na\'vi (uncredited)", "credit_id": "52fe48019251416c750acb6b", "gender": 0, "id": 103259, "name": "Nikie Zambo", "order": 81}, {"cast_id": 102, "character": "Ambient Room Tech / Troupe", "credit_id": "52fe48019251416c750acb6f", "gender": 1, "id": 42286, "name": "Julene Renee", "order": 82}]'

In [566]:
def convert2(obj):  
    l = []
    count = 0
    for i in ast.literal_eval(obj):
        if count < 3:
            l.append(i["name"])
            count+=1
        else:
            break
    return l
movie["cast"] = movie["cast"].apply(convert2)
movie.head(1)

,movie_id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"[In, the, 22nd, century,, a, paraplegic, Marin...","[Action, Adventure, Fantasy, Science Fiction]","[culture clash, future, space war, space colon...","[Sam Worthington, Zoe Saldana, Sigourney Weaver]","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."

In [567]:
ast.literal_eval(movie["crew"][0])

[{'credit_id': '52fe48009251416c750aca23',
  'department': 'Editing',
  'gender': 0,
  'id': 1721,
  'job': 'Editor',
  'name': 'Stephen E. Rivkin'},
 {'credit_id': '539c47ecc3a36810e3001f87',
  'department': 'Art',
  'gender': 2,
  'id': 496,
  'job': 'Production Design',
  'name': 'Rick Carter'},
 {'credit_id': '54491c89c3a3680fb4001cf7',
  'department': 'Sound',
  'gender': 0,
  'id': 900,
  'job': 'Sound Designer',
  'name': 'Christopher Boyes'},
 {'credit_id': '54491cb70e0a267480001bd0',
  'department': 'Sound',
  'gender': 0,
  'id': 900,
  'job': 'Supervising Sound Editor',
  'name': 'Christopher Boyes'},
 {'credit_id': '539c4a4cc3a36810c9002101',
  'department': 'Production',
  'gender': 1,
  'id': 1262,
  'job': 'Casting',
  'name': 'Mali Finn'},
 {'credit_id': '5544ee3b925141499f0008fc',
  'department': 'Sound',
  'gender': 2,
  'id': 1729,
  'job': 'Original Music Composer',
  'name': 'James Horner'},
 {'credit_id': '52fe48009251416c750ac9c3',
  'department': 'Directing',
  'gender': 2,
  'id': 2710,
  'job': 'Director',
  'name': 'James Cameron'},
 {'credit_id': '52fe48009251416c750ac9d9',
  'department': 'Writing',
  'gender': 2,
  'id': 2710,
  'job': 'Writer',
  'name': 'James Cameron'},
 {'credit_id': '52fe48009251416c750aca17',
  'department': 'Editing',
  'gender': 2,
  'id': 2710,
  'job': 'Editor',
  'name': 'James Cameron'},
 {'credit_id': '52fe48009251416c750aca29',
  'department': 'Production',
  'gender': 2,
  'id': 2710,
  'job': 'Producer',
  'name': 'James Cameron'},
 {'credit_id': '52fe48009251416c750aca3f',
  'department': 'Writing',
  'gender': 2,
  'id': 2710,
  'job': 'Screenplay',
  'name': 'James Cameron'},
 {'credit_id': '539c4987c3a36810ba0021a4',
  'department': 'Art',
  'gender': 2,
  'id': 7236,
  'job': 'Art Direction',
  'name': 'Andrew Menzies'},
 {'credit_id': '549598c3c3a3686ae9004383',
  'department': 'Visual Effects',
  'gender': 0,
  'id': 6690,
  'job': 'Visual Effects Producer',
  'name': 'Jill Brooks'},
 {'credit_id': '52fe48009251416c750aca4b',
  'department': 'Production',
  'gender': 1,
  'id': 6347,
  'job': 'Casting',
  'name': 'Margery Simkin'},
 {'credit_id': '570b6f419251417da70032fe',
  'department': 'Art',
  'gender': 2,
  'id': 6878,
  'job': 'Supervising Art Director',
  'name': 'Kevin Ishioka'},
 {'credit_id': '5495a0fac3a3686ae9004468',
  'department': 'Sound',
  'gender': 0,
  'id': 6883,
  'job': 'Music Editor',
  'name': 'Dick Bernstein'},
 {'credit_id': '54959706c3a3686af3003e81',
  'department': 'Sound',
  'gender': 0,
  'id': 8159,
  'job': 'Sound Effects Editor',
  'name': 'Shannon Mills'},
 {'credit_id': '54491d58c3a3680fb1001ccb',
  'department': 'Sound',
  'gender': 0,
  'id': 8160,
  'job': 'Foley',
  'name': 'Dennie Thorpe'},
 {'credit_id': '54491d6cc3a3680fa5001b2c',
  'department': 'Sound',
  'gender': 0,
  'id': 8163,
  'job': 'Foley',
  'name': 'Jana Vance'},
 {'credit_id': '52fe48009251416c750aca57',
  'department': 'Costume & Make-Up',
  'gender': 1,
  'id': 8527,
  'job': 'Costume Design',
  'name': 'Deborah Lynn Scott'},
 {'credit_id': '52fe48009251416c750aca2f',
  'department': 'Production',
  'gender': 2,
  'id': 8529,
  'job': 'Producer',
  'name': 'Jon Landau'},
 {'credit_id': '539c4937c3a36810ba002194',
  'department': 'Art',
  'gender': 0,
  'id': 9618,
  'job': 'Art Direction',
  'name': 'Sean Haworth'},
 {'credit_id': '539c49b6c3a36810c10020e6',
  'department': 'Art',
  'gender': 1,
  'id': 12653,
  'job': 'Set Decoration',
  'name': 'Kim Sinclair'},
 {'credit_id': '570b6f2f9251413a0e00020d',
  'department': 'Art',
  'gender': 1,
  'id': 12653,
  'job': 'Supervising Art Director',
  'name': 'Kim Sinclair'},
 {'credit_id': '54491a6c0e0a26748c001b19',
  'department': 'Art',
  'gender': 2,
  'id': 14350,
  'job': 'Set Designer',
  'name': 'Richard F. Mays'},
 {'credit_id': '56928cf4c3a3684cff0025c4',
  'department': 'Production',
  'gender': 1,
  'id': 20294,
  'job': 'Executive Producer',
  'name': 'Laeta Kalogridis'},
 {'credit_id': '52fe48009251416c750aca51',
  'department': 'Costume & Make-Up',
  'gender': 0,
  'id': 17675,
  'job': 'Costume Design',
  'name': 'Mayes C. Rubeo'},
 {'credit_id': '52fe48009251416c750aca11',
  'department': 'Camera',
  'gender': 2,
  'id': 18265,
  'job': 'Director of Photography',
  'name': 'Mauro Fiore'},
 {'credit_id': '5449194d0e0a26748f001b39',
  'department': 'Art',
  'gender': 0,
  'id': 42281,
  'job': 'Set Designer',
  'name': 'Scott Herbertson'},
 {'credit_id': '52fe48009251416c750aca05',
  'department': 'Crew',
  'gender': 0,
  'id': 42288,
  'job': 'Stunts',
  'name': 'Woody Schultz'},
 {'credit_id': '5592aefb92514152de0010f5',
  'department': 'Costume & Make-Up',
  'gender': 0,
  'id': 29067,
  'job': 'Makeup Artist',
  'name': 'Linda DeVetta'},
 {'credit_id': '5592afa492514152de00112c',
  'department': 'Costume & Make-Up',
  'gender': 0,
  'id': 29067,
  'job': 'Hairstylist',
  'name': 'Linda DeVetta'},
 {'credit_id': '54959ed592514130fc002e5d',
  'department': 'Camera',
  'gender': 2,
  'id': 33302,
  'job': 'Camera Operator',
  'name': 'Richard Bluck'},
 {'credit_id': '539c4891c3a36810ba002147',
  'department': 'Art',
  'gender': 2,
  'id': 33303,
  'job': 'Art Direction',
  'name': 'Simon Bright'},
 {'credit_id': '54959c069251417a81001f3a',
  'department': 'Visual Effects',
  'gender': 0,
  'id': 113145,
  'job': 'Visual Effects Supervisor',
  'name': 'Richard Martin'},
 {'credit_id': '54959a0dc3a3680ff5002c8d',
  'department': 'Crew',
  'gender': 2,
  'id': 58188,
  'job': 'Visual Effects Editor',
  'name': 'Steve R. Moore'},
 {'credit_id': '52fe48009251416c750aca1d',
  'department': 'Editing',
  'gender': 2,
  'id': 58871,
  'job': 'Editor',
  'name': 'John Refoua'},
 {'credit_id': '54491a4dc3a3680fc30018ca',
  'department': 'Art',
  'gender': 0,
  'id': 92359,
  'job': 'Set Designer',
  'name': 'Karl J. Martin'},
 {'credit_id': '52fe48009251416c750aca35',
  'department': 'Camera',
  'gender': 1,
  'id': 72201,
  'job': 'Director of Photography',
  'name': 'Chiling Lin'},
 {'credit_id': '52fe48009251416c750ac9ff',
  'department': 'Crew',
  'gender': 0,
  'id': 89714,
  'job': 'Stunts',
  'name': 'Ilram Choi'},
 {'credit_id': '54959c529251416e2b004394',
  'department': 'Visual Effects',
  'gender': 2,
  'id': 93214,
  'job': 'Visual Effects Supervisor',
  'name': 'Steven Quale'},
 {'credit_id': '54491edf0e0a267489001c37',
  'department': 'Crew',
  'gender': 1,
  'id': 122607,
  'job': 'Dialect Coach',
  'name': 'Carla Meyer'},
 {'credit_id': '539c485bc3a368653d001a3a',
  'department': 'Art',
  'gender': 2,
  'id': 132585,
  'job': 'Art Direction',
  'name': 'Nick Bassett'},
 {'credit_id': '539c4903c3a368653d001a74',
  'department': 'Art',
  'gender': 0,
  'id': 132596,
  'job': 'Art Direction',
  'name': 'Jill Cormack'},
 {'credit_id': '539c4967c3a368653d001a94',
  'department': 'Art',
  'gender': 0,
  'id': 132604,
  'job': 'Art Direction',
  'name': 'Andy McLaren'},
 {'credit_id': '52fe48009251416c750aca45',
  'department': 'Crew',
  'gender': 0,
  'id': 236696,
  'job': 'Motion Capture Artist',
  'name': 'Terry Notary'},
 {'credit_id': '54959e02c3a3680fc60027d2',
  'department': 'Crew',
  'gender': 2,
  'id': 956198,
  'job': 'Stunt Coordinator',
  'name': 'Garrett Warren'},
 {'credit_id': '54959ca3c3a3686ae300438c',
  'department': 'Visual Effects',
  'gender': 2,
  'id': 957874,
  'job': 'Visual Effects Supervisor',
  'name': 'Jonathan Rothbart'},
 {'credit_id': '570b6f519251412c74001b2f',
  'department': 'Art',
  'gender': 0,
  'id': 957889,
  'job': 'Supervising Art Director',
  'name': 'Stefan Dechant'},
 {'credit_id': '570b6f62c3a3680b77007460',
  'department': 'Art',
  'gender': 2,
  'id': 959555,
  'job': 'Supervising Art Director',
  'name': 'Todd Cherniawsky'},
 {'credit_id': '539c4a3ac3a36810da0021cc',
  'department': 'Production',
  'gender': 0,
  'id': 1016177,
  'job': 'Casting',
  'name': 'Miranda Rivers'},
 {'credit_id': '539c482cc3a36810c1002062',
  'department': 'Art',
  'gender': 0,
  'id': 1032536,
  'job': 'Production Design',
  'name': 'Robert Stromberg'},
 {'credit_id': '539c4b65c3a36810c9002125',
  'department': 'Costume & Make-Up',
  'gender': 2,
  'id': 1071680,
  'job': 'Costume Design',
  'name': 'John Harding'},
 {'credit_id': '54959e6692514130fc002e4e',
  'department': 'Camera',
  'gender': 0,
  'id': 1177364,
  'job': 'Steadicam Operator',
  'name': 'Roberto De Angelis'},
 {'credit_id': '539c49f1c3a368653d001aac',
  'department': 'Costume & Make-Up',
  'gender': 2,
  'id': 1202850,
  'job': 'Makeup Department Head',
  'name': 'Mike Smithson'},
 {'credit_id': '5495999ec3a3686ae100460c',
  'department': 'Visual Effects',
  'gender': 0,
  'id': 1204668,
  'job': 'Visual Effects Producer',
  'name': 'Alain Lalanne'},
 {'credit_id': '54959cdfc3a3681153002729',
  'department': 'Visual Effects',
  'gender': 0,
  'id': 1206410,
  'job': 'Visual Effects Supervisor',
  'name': 'Lucas Salton'},
 {'credit_id': '549596239251417a81001eae',
  'department': 'Crew',
  'gender': 0,
  'id': 1234266,
  'job': 'Post Production Supervisor',
  'name': 'Janace Tashjian'},
 {'credit_id': '54959c859251416e1e003efe',
  'department': 'Visual Effects',
  'gender': 0,
  'id': 1271932,
  'job': 'Visual Effects Supervisor',
  'name': 'Stephen Rosenbaum'},
 {'credit_id': '5592af28c3a368775a00105f',
  'department': 'Costume & Make-Up',
  'gender': 0,
  'id': 1310064,
  'job': 'Makeup Artist',
  'name': 'Frankie Karena'},
 {'credit_id': '539c4adfc3a36810e300203b',
  'department': 'Costume & Make-Up',
  'gender': 1,
  'id': 1319844,
  'job': 'Costume Supervisor',
  'name': 'Lisa Lovaas'},
 {'credit_id': '54959b579251416e2b004371',
  'department': 'Visual Effects',
  'gender': 0,
  'id': 1327028,
  'job': 'Visual Effects Supervisor',
  'name': 'Jonathan Fawkner'},
 {'credit_id': '539c48a7c3a36810b5001fa7',
  'department': 'Art',
  'gender': 0,
  'id': 1330561,
  'job': 'Art Direction',
  'name': 'Robert Bavin'},
 {'credit_id': '539c4a71c3a36810da0021e0',
  'department': 'Costume & Make-Up',
  'gender': 0,
  'id': 1330567,
  'job': 'Costume Supervisor',
  'name': 'Anthony Almaraz'},
 {'credit_id': '539c4a8ac3a36810ba0021e4',
  'department': 'Costume & Make-Up',
  'gender': 0,
  'id': 1330570,
  'job': 'Costume Supervisor',
  'name': 'Carolyn M. Fenton'},
 {'credit_id': '539c4ab6c3a36810da0021f0',
  'department': 'Costume & Make-Up',
  'gender': 0,
  'id': 1330574,
  'job': 'Costume Supervisor',
  'name': 'Beth Koenigsberg'},
 {'credit_id': '54491ab70e0a267480001ba2',
  'department': 'Art',
  'gender': 0,
  'id': 1336191,
  'job': 'Set Designer',
  'name': 'Sam Page'},
 {'credit_id': '544919d9c3a3680fc30018bd',
  'department': 'Art',
  'gender': 0,
  'id': 1339441,
  'job': 'Set Designer',
  'name': 'Tex Kadonaga'},
 {'credit_id': '54491cf50e0a267483001b0c',
  'department': 'Editing',
  'gender': 0,
  'id': 1352422,
  'job': 'Dialogue Editor',
  'name': 'Kim Foscato'},
 {'credit_id': '544919f40e0a26748c001b09',
  'department': 'Art',
  'gender': 0,
  'id': 1352962,
  'job': 'Set Designer',
  'name': 'Tammy S. Lee'},
 {'credit_id': '5495a115c3a3680ff5002d71',
  'department': 'Crew',
  'gender': 0,
  'id': 1357070,
  'job': 'Transportation Coordinator',
  'name': 'Denny Caira'},
 {'credit_id': '5495a12f92514130fc002e94',
  'department': 'Crew',
  'gender': 0,
  'id': 1357071,
  'job': 'Transportation Coordinator',
  'name': 'James Waitkus'},
 {'credit_id': '5495976fc3a36811530026b0',
  'department': 'Sound',
  'gender': 0,
  'id': 1360103,
  'job': 'Supervising Sound Editor',
  'name': 'Addison Teague'},
 {'credit_id': '54491837c3a3680fb1001c5a',
  'department': 'Art',
  'gender': 2,
  'id': 1376887,
  'job': 'Set Designer',
  'name': 'C. Scott Baker'},
 {'credit_id': '54491878c3a3680fb4001c9d',
  'department': 'Art',
  'gender': 0,
  'id': 1376888,
  'job': 'Set Designer',
  'name': 'Luke Caska'},
 {'credit_id': '544918dac3a3680fa5001ae0',
  'department': 'Art',
  'gender': 0,
  'id': 1376889,
  'job': 'Set Designer',
  'name': 'David Chow'},
 {'credit_id': '544919110e0a267486001b68',
  'department': 'Art',
  'gender': 0,
  'id': 1376890,
  'job': 'Set Designer',
  'name': 'Jonathan Dyer'},
 {'credit_id': '54491967c3a3680faa001b5e',
  'department': 'Art',
  'gender': 0,
  'id': 1376891,
  'job': 'Set Designer',
  'name': 'Joseph Hiura'},
 {'credit_id': '54491997c3a3680fb1001c8a',
  'department': 'Art',
  'gender': 0,
  'id': 1376892,
  'job': 'Art Department Coordinator',
  'name': 'Rebecca Jellie'},
 {'credit_id': '544919ba0e0a26748f001b42',
  'department': 'Art',
  'gender': 0,
  'id': 1376893,
  'job': 'Set Designer',
  'name': 'Robert Andrew Johnson'},
 {'credit_id': '54491b1dc3a3680faa001b8c',
  'department': 'Art',
  'gender': 0,
  'id': 1376895,
  'job': 'Assistant Art Director',
  'name': 'Mike Stassi'},
 {'credit_id': '54491b79c3a3680fbb001826',
  'department': 'Art',
  'gender': 0,
  'id': 1376897,
  'job': 'Construction Coordinator',
  'name': 'John Villarino'},
 {'credit_id': '54491baec3a3680fb4001ce6',
  'department': 'Art',
  'gender': 2,
  'id': 1376898,
  'job': 'Assistant Art Director',
  'name': 'Jeffrey Wisniewski'},
 {'credit_id': '54491d2fc3a3680fb4001d07',
  'department': 'Editing',
  'gender': 0,
  'id': 1376899,
  'job': 'Dialogue Editor',
  'name': 'Cheryl Nardi'},
 {'credit_id': '54491d86c3a3680fa5001b2f',
  'department': 'Editing',
  'gender': 0,
  'id': 1376901,
  'job': 'Dialogue Editor',
  'name': 'Marshall Winn'},
 {'credit_id': '54491d9dc3a3680faa001bb0',
  'department': 'Sound',
  'gender': 0,
  'id': 1376902,
  'job': 'Supervising Sound Editor',
  'name': 'Gwendolyn Yates Whittle'},
 {'credit_id': '54491dc10e0a267486001bce',
  'department': 'Sound',
  'gender': 0,
  'id': 1376903,
  'job': 'Sound Re-Recording Mixer',
  'name': 'William Stein'},
 {'credit_id': '54491f500e0a26747c001c07',
  'department': 'Crew',
  'gender': 0,
  'id': 1376909,
  'job': 'Choreographer',
  'name': 'Lula Washington'},
 {'credit_id': '549599239251412c4e002a2e',
  'department': 'Visual Effects',
  'gender': 0,
  'id': 1391692,
  'job': 'Visual Effects Producer',
  'name': 'Chris Del Conte'},
 {'credit_id': '54959d54c3a36831b8001d9a',
  'department': 'Visual Effects',
  'gender': 2,
  'id': 1391695,
  'job': 'Visual Effects Supervisor',
  'name': 'R. Christopher White'},
 {'credit_id': '54959bdf9251412c4e002a66',
  'department': 'Visual Effects',
  'gender': 0,
  'id': 1394070,
  'job': 'Visual Effects Supervisor',
  'name': 'Dan Lemmon'},
 {'credit_id': '5495971d92514132ed002922',
  'department': 'Sound',
  'gender': 0,
  'id': 1394129,
  'job': 'Sound Effects Editor',
  'name': 'Tim Nielsen'},
 {'credit_id': '5592b25792514152cc0011aa',
  'department': 'Crew',
  'gender': 0,
  'id': 1394286,
  'job': 'CG Supervisor',
  'name': 'Michael Mulholland'},
 {'credit_id': '54959a329251416e2b004355',
  'department': 'Crew',
  'gender': 0,
  'id': 1394750,
  'job': 'Visual Effects Editor',
  'name': 'Thomas Nittmann'},
 {'credit_id': '54959d6dc3a3686ae9004401',
  'department': 'Visual Effects',
  'gender': 0,
  'id': 1394755,
  'job': 'Visual Effects Supervisor',
  'name': 'Edson Williams'},
 {'credit_id': '5495a08fc3a3686ae300441c',
  'department': 'Editing',
  'gender': 0,
  'id': 1394953,
  'job': 'Digital Intermediate',
  'name': 'Christine Carr'},
 {'credit_id': '55402d659251413d6d000249',
  'department': 'Visual Effects',
  'gender': 0,
  'id': 1395269,
  'job': 'Visual Effects Supervisor',
  'name': 'John Bruno'},
 {'credit_id': '54959e7b9251416e1e003f3e',
  'department': 'Camera',
  'gender': 0,
  'id': 1398970,
  'job': 'Steadicam Operator',
  'name': 'David Emmerichs'},
 {'credit_id': '54959734c3a3686ae10045e0',
  'department': 'Sound',
  'gender': 0,
  'id': 1400906,
  'job': 'Sound Effects Editor',
  'name': 'Christopher Scarabosio'},
 {'credit_id': '549595dd92514130fc002d79',
  'department': 'Production',
  'gender': 0,
  'id': 1401784,
  'job': 'Production Supervisor',
  'name': 'Jennifer Teves'},
 {'credit_id': '549596009251413af70028cc',
  'department': 'Production',
  'gender': 0,
  'id': 1401785,
  'job': 'Production Manager',
  'name': 'Brigitte Yorke'},
 {'credit_id': '549596e892514130fc002d99',
  'department': 'Sound',
  'gender': 0,
  'id': 1401786,
  'job': 'Sound Effects Editor',
  'name': 'Ken Fischer'},
 {'credit_id': '549598229251412c4e002a1c',
  'department': 'Crew',
  'gender': 0,
  'id': 1401787,
  'job': 'Special Effects Coordinator',
  'name': 'Iain Hutton'},
 {'credit_id': '549598349251416e2b00432b',
  'department': 'Crew',
  'gender': 0,
  'id': 1401788,
  'job': 'Special Effects Coordinator',
  'name': 'Steve Ingram'},
 {'credit_id': '54959905c3a3686ae3004324',
  'department': 'Visual Effects',
  'gender': 0,
  'id': 1401789,
  'job': 'Visual Effects Producer',
  'name': 'Joyce Cox'},
 {'credit_id': '5495994b92514132ed002951',
  'department': 'Visual Effects',
  'gender': 0,
  'id': 1401790,
  'job': 'Visual Effects Producer',
  'name': 'Jenny Foster'},
 {'credit_id': '549599cbc3a3686ae1004613',
  'department': 'Crew',
  'gender': 0,
  'id': 1401791,
  'job': 'Visual Effects Editor',
  'name': 'Christopher Marino'},
 {'credit_id': '549599f2c3a3686ae100461e',
  'department': 'Crew',
  'gender': 0,
  'id': 1401792,
  'job': 'Visual Effects Editor',
  'name': 'Jim Milton'},
 {'credit_id': '54959a51c3a3686af3003eb5',
  'department': 'Visual Effects',
  'gender': 0,
  'id': 1401793,
  'job': 'Visual Effects Producer',
  'name': 'Cyndi Ochs'},
 {'credit_id': '54959a7cc3a36811530026f4',
  'department': 'Crew',
  'gender': 0,
  'id': 1401794,
  'job': 'Visual Effects Editor',
  'name': 'Lucas Putnam'},
 {'credit_id': '54959b91c3a3680ff5002cb4',
  'department': 'Visual Effects',
  'gender': 0,
  'id': 1401795,
  'job': 'Visual Effects Supervisor',
  'name': "Anthony 'Max' Ivins"},
 {'credit_id': '54959bb69251412c4e002a5f',
  'department': 'Visual Effects',
  'gender': 0,
  'id': 1401796,
  'job': 'Visual Effects Supervisor',
  'name': 'John Knoll'},
 {'credit_id': '54959cbbc3a3686ae3004391',
  'department': 'Visual Effects',
  'gender': 2,
  'id': 1401799,
  'job': 'Visual Effects Supervisor',
  'name': 'Eric Saindon'},
 {'credit_id': '54959d06c3a3686ae90043f6',
  'department': 'Visual Effects',
  'gender': 0,
  'id': 1401800,
  'job': 'Visual Effects Supervisor',
  'name': 'Wayne Stables'},
 {'credit_id': '54959d259251416e1e003f11',
  'department': 'Visual Effects',
  'gender': 0,
  'id': 1401801,
  'job': 'Visual Effects Supervisor',
  'name': 'David Stinnett'},
 {'credit_id': '54959db49251413af7002975',
  'department': 'Visual Effects',
  'gender': 0,
  'id': 1401803,
  'job': 'Visual Effects Supervisor',
  'name': 'Guy Williams'},
 {'credit_id': '54959de4c3a3681153002750',
  'department': 'Crew',
  'gender': 0,
  'id': 1401804,
  'job': 'Stunt Coordinator',
  'name': 'Stuart Thorp'},
 {'credit_id': '54959ef2c3a3680fc60027f2',
  'department': 'Lighting',
  'gender': 0,
  'id': 1401805,
  'job': 'Best Boy Electric',
  'name': 'Giles Coburn'},
 {'credit_id': '54959f07c3a3680fc60027f9',
  'department': 'Camera',
  'gender': 2,
  'id': 1401806,
  'job': 'Still Photographer',
  'name': 'Mark Fellman'},
 {'credit_id': '54959f47c3a3681153002774',
  'department': 'Lighting',
  'gender': 0,
  'id': 1401807,
  'job': 'Lighting Technician',
  'name': 'Scott Sprague'},
 {'credit_id': '54959f8cc3a36831b8001df2',
  'department': 'Visual Effects',
  'gender': 0,
  'id': 1401808,
  'job': 'Animation Director',
  'name': 'Jeremy Hollobon'},
 {'credit_id': '54959fa0c3a36831b8001dfb',
  'department': 'Visual Effects',
  'gender': 0,
  'id': 1401809,
  'job': 'Animation Director',
  'name': 'Orlando Meunier'},
 {'credit_id': '54959fb6c3a3686af3003f54',
  'department': 'Visual Effects',
  'gender': 0,
  'id': 1401810,
  'job': 'Animation Director',
  'name': 'Taisuke Tanimura'},
 {'credit_id': '54959fd2c3a36831b8001e02',
  'department': 'Costume & Make-Up',
  'gender': 0,
  'id': 1401812,
  'job': 'Set Costumer',
  'name': 'Lilia Mishel Acevedo'},

In [568]:
def fetch_director(obj):
    l = []
    for i in ast.literal_eval(obj):
        if i["job"] == "Director":
            l.append(i["name"])
            break
    return l

movie["crew"] = movie["crew"].apply(fetch_director)
movie.head(1)

,movie_id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"[In, the, 22nd, century,, a, paraplegic, Marin...","[Action, Adventure, Fantasy, Science Fiction]","[culture clash, future, space war, space colon...","[Sam Worthington, Zoe Saldana, Sigourney Weaver]",[James Cameron]

### data transformation
#### remove space
example || 
input => aman kashyap,
output => amankashyap

In [569]:
movie["genres"] = movie["genres"].apply(lambda x: [i.replace(" ","") for i in x])
movie["genres"].head(3)

0    [Action, Adventure, Fantasy, ScienceFiction]
1                    [Adventure, Fantasy, Action]
2                      [Action, Adventure, Crime]
Name: genres, dtype: object

In [570]:
movie["keywords"] = movie["keywords"].apply(lambda x: [i.replace(" ","") for i in x])
movie["cast"] = movie["cast"].apply(lambda x: [i.replace(" ","") for i in x])
movie["crew"] = movie["crew"].apply(lambda x: [i.replace(" ","") for i in x])
movie.head(1)

,movie_id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"[In, the, 22nd, century,, a, paraplegic, Marin...","[Action, Adventure, Fantasy, ScienceFiction]","[cultureclash, future, spacewar, spacecolony, ...","[SamWorthington, ZoeSaldana, SigourneyWeaver]",[JamesCameron]

In [571]:
movie["tags"] = movie["overview"] + movie["genres"] + movie["keywords"] + movie["cast"] + movie["crew"]
movie["tags"].head(1)

0    [In, the, 22nd, century,, a, paraplegic, Marin...
Name: tags, dtype: object

In [572]:
movie.head(1)

,movie_id,title,overview,genres,keywords,cast,crew,tags
0,19995,Avatar,"[In, the, 22nd, century,, a, paraplegic, Marin...","[Action, Adventure, Fantasy, ScienceFiction]","[cultureclash, future, spacewar, spacecolony, ...","[SamWorthington, ZoeSaldana, SigourneyWeaver]",[JamesCameron],"[In, the, 22nd, century,, a, paraplegic, Marin..."

In [573]:
new_df = movie[["movie_id", "title", "tags"]]
new_df.head(1)

   movie_id   title                                               tags
0     19995  Avatar  [In, the, 22nd, century,, a, paraplegic, Marin...

In [574]:
new_df["tags"] = new_df["tags"].apply(lambda x: " ".join(x))

C:\Users\kashy\AppData\Local\Temp\ipykernel_25936\3719869087.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df["tags"] = new_df["tags"].apply(lambda x: " ".join(x))

In [575]:
new_df["tags"][0]

'In the 22nd century, a paraplegic Marine is dispatched to the moon Pandora on a unique mission, but becomes torn between following orders and protecting an alien civilization. Action Adventure Fantasy ScienceFiction cultureclash future spacewar spacecolony society spacetravel futuristic romance space alien tribe alienplanet cgi marine soldier battle loveaffair antiwar powerrelations mindandsoul 3d SamWorthington ZoeSaldana SigourneyWeaver JamesCameron'

In [576]:
new_df["tags"] = new_df["tags"].apply(lambda x:x.lower())
new_df["tags"].sample(1)

C:\Users\kashy\AppData\Local\Temp\ipykernel_25936\596098642.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df["tags"] = new_df["tags"].apply(lambda x:x.lower())

1578    two best friends become rivals when their resp...
Name: tags, dtype: object

## apply stemimg which remove the same words
### example || input => [loved, loving, love], output => [love]

In [577]:
import nltk 
from nltk.stem.porter import PorterStemmer
ps = PorterStemmer()

In [578]:
# example 
ps.stem("loving", "lover")

'love'

In [579]:
def stemming(text):
    y = []
    for i in text.split():
        y.append(ps.stem(i))
    return " ".join(y)

In [580]:
steming('In the 22nd century, a paraplegic Marine is dispatched to the moon Pandora on a unique mission, but becomes torn between following orders and protecting an alien civilization. Action Adventure Fantasy ScienceFiction cultureclash future spacewar spacecolony society spacetravel futuristic romance space alien tribe alienplanet cgi marine soldier battle loveaffair antiwar powerrelations mindandsoul 3d SamWorthington ZoeSaldana SigourneyWeaver JamesCameron')

'in the 22nd century, a parapleg marin is dispatch to the moon pandora on a uniqu mission, but becom torn between follow order and protect an alien civilization. action adventur fantasi sciencefict cultureclash futur spacewar spacecoloni societi spacetravel futurist romanc space alien tribe alienplanet cgi marin soldier battl loveaffair antiwar powerrel mindandsoul 3d samworthington zoesaldana sigourneyweav jamescameron'

In [581]:
new_df["tags"] = new_df["tags"].apply(stemming)
new_df["tags"][0]

C:\Users\kashy\AppData\Local\Temp\ipykernel_25936\3082329780.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df["tags"] = new_df["tags"].apply(stemming)

'in the 22nd century, a parapleg marin is dispatch to the moon pandora on a uniqu mission, but becom torn between follow order and protect an alien civilization. action adventur fantasi sciencefict cultureclash futur spacewar spacecoloni societi spacetravel futurist romanc space alien tribe alienplanet cgi marin soldier battl loveaffair antiwar powerrel mindandsoul 3d samworthington zoesaldana sigourneyweav jamescameron'

In [582]:
new_df.sample(1)

,movie_id,title,tags
1678,50135,Animals United,a group of anim wait for the annual flood they...

### Vactorization

In [583]:
from sklearn.feature_extraction.text import CountVectorizer 
cv = CountVectorizer(max_features=5000, stop_words="english")  # it return parse matrix
vectors = cv.fit_transform(new_df["tags"]).toarray()
vectors

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [584]:
vectors.shape

(4806, 5000)

In [585]:
vectors[0]

array([0, 0, 0, ..., 0, 0, 0], dtype=int64)

In [586]:
# this 5000 words come most come of the amoung tags
print(len(cv.get_feature_names_out())) #arrange in alphabatic
cv.get_feature_names_out()

5000

array(['000', '007', '10', ..., 'zone', 'zoo', 'zooeydeschanel'],
      dtype=object)

In [587]:
from sklearn.metrics.pairwise import cosine_similarity

In [588]:
similarity = cosine_similarity(vectors)
similarity

array([[1.        , 0.08346223, 0.0860309 , ..., 0.04499213, 0.        ,
        0.        ],
       [0.08346223, 1.        , 0.06063391, ..., 0.02378257, 0.        ,
        0.02615329],
       [0.0860309 , 0.06063391, 1.        , ..., 0.02451452, 0.        ,
        0.        ],
       ...,
       [0.04499213, 0.02378257, 0.02451452, ..., 1.        , 0.03962144,
        0.04229549],
       [0.        , 0.        , 0.        , ..., 0.03962144, 1.        ,
        0.08714204],
       [0.        , 0.02615329, 0.        , ..., 0.04229549, 0.08714204,
        1.        ]])

In [589]:
cosine_similarity(vectors).shape

(4806, 4806)

In [590]:
similarity[0]

array([1.        , 0.08346223, 0.0860309 , ..., 0.04499213, 0.        ,
       0.        ])

In [591]:
# sns.heatmap(cosine_similarity(vectors))

In [592]:
new_df[new_df["title"]=="Avatar"]

   movie_id   title                                               tags
0     19995  Avatar  in the 22nd century, a parapleg marin is dispa...

In [593]:
# problem is that index is loss
sorted(similarity[0], reverse=True)

[1.0000000000000002,
 0.28676966733820225,
 0.26901379342448517,
 0.2605130246476754,
 0.255608593705383,
 0.2503866978335957,
 0.24511108480187255,
 0.24455799402225925,
 0.2367785320221084,
 0.23179316248638274,
 0.23174488732966075,
 0.2278389747471728,
 0.22528177844479153,
 0.21853668936906193,
 0.21239769762143662,
 0.2108663315950723,
 0.2105263157894737,
 0.20443988269091456,
 0.20437977982832192,
 0.20395079136182276,
 0.2029530274475215,
 0.2029530274475215,
 0.20277677641345318,
 0.20246457179963143,
 0.2020475485519274,
 0.1979082783981174,
 0.19767387315371682,
 0.1976738731537168,
 0.19672236884115843,
 0.19252140716412977,
 0.19134594929397597,
 0.19088542889273336,
 0.19088542889273336,
 0.1900748713929803,
 0.18929940971212042,
 0.18731716231633883,
 0.1873171623163388,
 0.18693292157876878,
 0.1860807318911967,
 0.18394180184548975,
 0.18394180184548975,
 0.1813690625275029,
 0.18074256993863339,
 0.17996850826633903,
 0.17954621161490197,
 0.1777046633277277,
 0.177343107178349,
 0.17699808135119718,
 0.17521916101261562,
 0.17521916101261562,
 0.17521916101261562,
 0.1748149640244195,
 0.17316974359835272,
 0.17292861596651865,
 0.1711905958155815,
 0.1711905958155815,
 0.17040572913692198,
 0.16943474841747153,
 0.1675415633166782,
 0.16742770563222897,
 0.16742770563222897,
 0.16692446522239718,
 0.16563698349810535,
 0.16452254913212452,
 0.16426202236672155,
 0.16222142113076254,
 0.16122923187750418,
 0.16059101370939324,
 0.15907119074394446,
 0.15907119074394446,
 0.15789473684210528,
 0.15737789507292674,
 0.15609763526361567,
 0.15511334686589626,
 0.1540171257313038,
 0.15389675281277312,
 0.15389675281277312,
 0.152008377581442,
 0.15018785229652767,
 0.15018785229652767,
 0.15018785229652765,
 0.14843120879858804,
 0.14843120879858804,
 0.14808721943977307,
 0.14673479641335554,
 0.14659886790209342,
 0.14601068654819693,
 0.14567913668701626,
 0.14567913668701626,
 0.14509525002200235,
 0.14509525002200235,
 0.14509525002200233,
 0.14421498760030763,
 0.14421498760030763,
 0.14350946197048198,
 0.14350946197048198,
 0.1433848336691011,
 0.1433848336691011,
 0.1433848336691011,
 0.1419745572840903,
 0.1419745572840903,
 0.14159846508095775,
 0.14159846508095775,
 0.1411956236812263,
 0.1411956236812263,
 0.1411956236812263,
 0.1411956236812263,
 0.1404878717372541,
 0.13977653617040256,
 0.1391037210186643,
 0.1391037210186643,
 0.13872950617564817,
 0.13834289277321493,
 0.13834289277321493,
 0.13834289277321493,
 0.13834289277321493,
 0.13710212427677043,
 0.13710212427677043,
 0.13710212427677043,
 0.13710212427677043,
 0.13629325512727639,
 0.13530201829834768,
 0.13530201829834768,
 0.13530201829834768,
 0.13530201829834768,
 0.13530201829834768,
 0.13518451760896877,
 0.13497638119975428,
 0.13476498501489081,
 0.13369695534647594,
 0.13369695534647594,
 0.13369695534647594,
 0.13334518676566626,
 0.13334518676566626,
 0.1324532357065044,
 0.1324532357065044,
 0.1324532357065044,
 0.13157894736842107,
 0.13124359177794215,
 0.12988108336653278,
 0.12988108336653278,
 0.12988108336653278,
 0.12977713690461004,
 0.12977713690461004,
 0.12977713690461004,
 0.12892051277806202,
 0.12824729401064427,
 0.12824729401064427,
 0.12824729401064427,
 0.12824729401064427,
 0.12824729401064427,
 0.12824729401064427,
 0.12725695259515557,
 0.12725695259515557,
 0.12725695259515557,
 0.126673647984535,
 0.12565617248750865,
 0.12565617248750865,
 0.12515654358043973,
 0.12515654358043973,
 0.12515654358043973,
 0.12515654358043973,
 0.12487810821089254,
 0.12487810821089254,
 0.12487810821089254,
 0.12487810821089254,
 0.12462194771917919,
 0.12361284651454937,
 0.12262786789699316,
 0.12262786789699316,
 0.12262786789699315,
 0.12227899701112963,
 0.12227899701112963,
 0.12227899701112963,
 0.12166606584807191,
 0.12166606584807191,
 0.12166606584807191,
 0.12072654548783007,
 0.1204950466257556,
 0.1204950466257556,
 0.1204950466257556,
 0.1204950466257556,
 0.1204950466257556,
 0.11980845957463077,
 0.11959121830873498,
 0.11959121830873498,
 0.11959121830873498,
 0.11959121830873498,
 0.11846977555181847,
 0.11846977555181847,
 0.11846977555181847,
 0.11846977555181847,
 0.11846977555181847,
 0.11803342130469506,
 0.11803342130469506,
 0.11803342130469505,
 0.11803342130469505,
 0.11803342130469505,
 0.11712303424679457,
 0.11707322644771176,
 0.11707322644771176,
 0.11707322644771176,
 0.11707322644771176,
 0.11707322644771176,
 0.116543309349613,
 0.116543309349613,
 0.116543309349613,
 0.116543309349613,
 0.1163350101494222,
 0.11587244366483038,
 0.11551284429847784,
 0.11506355109724453,
 0.1147078669352809,
 0.11470786693528089,
 0.11470786693528087,
 0.11470786693528087,
 0.11412706387705432,
 0.11357771260606365,
 0.11357771260606365,
 0.11295649894498103,
 0.11295649894498103,
 0.1124803176664619,
 0.1124803176664619,
 0.1124803176664619,
 0.11243619908556624,
 0.11239029738980327,
 0.11164843913471803,
 0.11164843913471803,
 0.11164843913471803,
 0.11164843913471803,
 0.11141412945539662,
 0.11141412945539661,
 0.11141412945539661,
 0.11128297681493143,
 0.11128297681493143,
 0.11128297681493143,
 0.11128297681493143,
 0.11092107999698035,
 0.11092107999698035,
 0.11037769642208699,
 0.11020775375559676,
 0.11020775375559674,
 0.10968169942141637,
 0.10968169942141635,
 0.10968169942141635,
 0.10968169942141635,
 0.10968169942141635,
 0.10968169942141635,
 0.10968169942141635,
 0.10936965981495178,
 0.10882143751650175,
 0.10882143751650175,
 0.10882143751650175,
 0.10882143751650175,
 0.10876595882948199,
 0.10838874619051501,
 0.10838874619051501,
 0.10838874619051501,
 0.108388746190515,
 0.10814761408717502,
 0.10814761408717502,
 0.10814761408717502,
 0.1074861545850028,
 0.10743376064838502,
 0.1068366854693644,
 0.106676149412533,
 0.106676149412533,
 0.106676149412533,
 0.10650358071057624,
 0.10650358071057624,
 0.10619884881071831,
 0.10619884881071831,
 0.10619884881071831,
 0.10619884881071831,
 0.10619884881071831,
 0.10619884881071831,
 0.10559715077387793,
 0.10559715077387793,
 0.10559715077387793,
 0.10526315789473685,
 0.10526315789473685,
 0.10526315789473685,
 0.10526315789473685,
 0.10471347707292387,
 0.10390486669322622,
 0.10390486669322622,
 0.10390486669322622,
 0.10390486669322622,
 0.10390486669322622,
 0.10390486669322622,
 0.10390486669322622,
 0.103851623099316,
 0.10385162309931599,
 0.1037571695799112,
 0.1037571695799112,
 0.1037571695799112,
 0.1037571695799112,
 0.1037571695799112,
 0.1037571695799112,
 0.1037571695799112,
 0.1037571695799112,
 0.1037571695799112,
 0.10301070542879115,
 0.10259783520851541,
 0.10259783520851541,
 0.10259783520851541,
 0.10259783520851541,
 0.10259783520851541,
 0.10259783520851541,
 0.10259783520851541,
 0.10218988991416095,
 0.10147651372376076,
 0.10147651372376076,
 0.10147651372376076,
 0.10138838820672659,
 0.101338918387628,
 0.101338918387628,
 0.10133891838762799,
 0.10060545457319173,
 0.10060545457319173,
 0.10060545457319173,
 0.10012523486435178,
 0.10012523486435178,
 0.10012523486435178,
 0.10012523486435178,
 0.10012523486435178,
 0.10012523486435178,
 0.09933992677987831,
 0.09933992677987831,
 0.09933992677987831,
 0.09933992677987831,
 0.09933992677987831,
 0.09933992677987831,
 0.09933992677987831,
 0.09933992677987831,
 0.09933992677987831,
 0.09933992677987831,
 0.09933992677987831,
 0.09933992677987831,
 0.09909250441117726,
 0.09909250441117726,
 0.0989541391990587,
 0.0989541391990587,
 0.0989541391990587,
 0.0989541391990587,
 0.0989541391990587,
 0.0989541391990587,
 0.09836118442057921,
 0.0978231976089037,
 0.0978231976089037,
 0.0978231976089037,
 0.0978231976089037,
 0.0978231976089037,
 0.0978231976089037,
 0.0978231976089037,
 0.0978231976089037,
 0.09733285267845754,
 0.09733285267845754,
 0.09733285267845754,
 0.09733285267845754,
 0.09733285267845754,
 0.09733285267845754,
 0.09733285267845754,
 0.09733285267845754,
 0.09733285267845754,
 0.09733285267845754,
 0.09733285267845754,
 0.0967301666813349,
 0.0967301666813349,
 0.09567297464698798,
 0.09567297464698798,
 0.09567297464698798,
 0.09567297464698798,
 0.09558988911273408,
 0.09544271444636668,
 0.09544271444636668,
 0.09544271444636668,
 0.09544271444636668,
 0.09544271444636668,
 0.09493290614465533,
 0.09464970485606021,
 0.09464970485606021,
 0.09365858115816941,
 0.09365858115816941,
 0.09365858115816941,
 0.09365858115816941,
 0.09365858115816941,
 0.09365858115816941,
 0.09365858115816941,
 0.09365858115816941,
 0.09365858115816941,
 0.09365858115816941,
 0.09365858115816941,
 0.09365858115816941,
 0.09365858115816941,
 0.09365858115816941,
 0.09365858115816941,
 0.09365858115816941,
 0.09365858115816941,
 0.09365858115816941,
 0.09365858115816941,
 0.09365858115816939,
 0.09269795493186431,
 0.09269795493186431,
 0.09269795493186431,
 0.09269795493186431,
 0.09269795493186431,
 0.09269795493186431,
 0.09269795493186431,
 0.09269795493186431,
 0.09269795493186431,
 0.09243423333081695,
 0.09197090092274487,
 0.09197090092274487,
 0.09197090092274487,
 0.09197090092274487,
 0.09197090092274487,
 0.09197090092274487,
 0.09197090092274487,
 0.09183979479633063,
 0.09183979479633063,
 0.09125667909262308,
 0.09125667909262308,
 0.09086217008485092,
 0.09086217008485092,
 0.09086217008485092,
 0.09086217008485092,
 0.09086217008485092,
 0.09086217008485092,
 0.09037128496931669,
 0.09037128496931669,
 0.09037128496931669,
 0.09037128496931669,
 0.09037128496931669,
 0.09037128496931669,
 0.09037128496931669,
 0.09037128496931669,
 0.09037128496931669,
 0.08998425413316952,
 0.08998425413316952,
 0.08998425413316952,
 0.08998425413316952,
 0.08998425413316952,
 0.08998425413316952,
 0.08998425413316952,
 0.08998425413316952,
 0.08998425413316952,
 0.08977310580745099,
 0.0891313035643173,
 0.08903057122447033,
 0.08885233166386385,
 0.08885233166386385,
 0.08885233166386385,
 0.08885233166386385,
 0.08885233166386385,
 0.08885233166386385,
 0.08830215713766959,
 0.08830215713766959,
 0.08830215713766959,
 0.08830215713766959,
 0.08830215713766959,
 0.08830215713766959,
 0.08830215713766959,
 0.08830215713766959,
 0.08797691788472335,
 0.08749572785196143,
 0.08749572785196143,
 0.08746392856766495,
 0.08740748201220976,
 0.08740748201220976,
 0.08740748201220976,
 0.08740748201220976,
 0.08740748201220976,
 0.08740748201220976,
 0.08740748201220976,
 0.08740748201220976,
 0.08740748201220976,
 0.08740748201220976,
 0.08671099695241201,
 0.08671099695241201,
 0.08671099695241201,
 0.08671099695241201,
 0.08671099695241201,
 0.08671099695241201,
 0.08671099695241201,
 0.08671099695241201,
 0.08603090020146065,
 0.08603090020146065,
 0.08603090020146065,
 0.08603090020146065,
 0.08603090020146065,
 0.08603090020146065,
 0.08603090020146065,
 0.08594700851870801,
 0.08594700851870801,
 0.08594700851870801,
 0.08520286456846099,
 0.08520286456846099,
 0.08471737420873576,
 0.08471737420873576,
 0.08471737420873576,
 0.08471737420873576,
 0.08471737420873576,
 0.08471737420873576,
 0.08471737420873576,
 0.08447772061910234,
 0.08447772061910234,
 0.08447772061910234,
 0.08447772061910234,
 0.08447772061910234,
 0.0837707816583391,
 0.0837707816583391,
 0.0837707816583391,
 0.0837707816583391,
 0.0837707816583391,
 0.0837707816583391,
 0.0837707816583391,
 0.0837707816583391,
 0.08346223261119858,
 0.08346223261119858,
 0.08346223261119858,
 0.08346223261119858,
 0.08346223261119858,
 0.08346223261119858,
 0.08346223261119858,
 0.08321783316232578,
 0.0830812984794528,
 0.0830812984794528,
 0.0830812984794528,
 0.08240856434303293,
 0.08240856434303293,
 0.08226127456606226,
 0.08226127456606226,
 0.08226127456606226,
 0.08226127456606226,
 0.08226127456606226,
 0.08226127456606226,
 0.08226127456606226,
 0.08226127456606226,
 0.08226127456606226,
 0.08226127456606226,
 0.08226127456606226,
 0.08226127456606226,
 0.08175191193132876,
 0.08175191193132876,
 0.08111071056538127,
 0.08111071056538127,
 0.08111071056538127,
 0.08111071056538127,
 0.08111071056538127,
 0.08111071056538127,
 0.08111071056538127,
 0.08111071056538127,
 0.08111071056538127,
 0.08111071056538127,
 0.08111071056538127,
 0.08111071056538127,
 0.08111071056538127,
 0.08111071056538127,
 0.08111071056538127,
 0.08111071056538127,
 0.08111071056538127,
 0.08111071056538127,
 0.08111071056538127,
 0.08111071056538127,
 0.08111071056538127,
 0.08111071056538127,
 0.08111071056538127,
 0.08111071056538127,
 0.08048436365855338,
 0.08000711205939975,
 0.08000711205939975,
 0.08000711205939975,
 0.08000711205939975,
 0.08000711205939975,
 0.08000711205939975,
 0.08000711205939975,
 0.08000711205939975,
 0.08000711205939975,
 0.07992075789278003,
 0.07987230638308718,
 0.07987230638308718,
 0.07987230638308718,
 0.07987230638308718,
 0.07987230638308718,
 0.0792740035289418,
 0.07894736842105264,
 0.07894736842105264,
 0.07894736842105264,
 0.07894736842105264,
 0.07894736842105264,
 0.07894736842105264,
 0.07894736842105264,
 0.07894736842105264,
 0.07894736842105264,
 0.07878168645790681,
 0.07868894753646337,
 0.07868894753646337,
 0.07868894753646337,
 0.07868894753646337,
 0.07868894753646337,
 0.07868894753646337,
 0.07868894753646337,
 0.07868894753646337,
 0.07868894753646337,
 0.07843304784240032,
 0.0781166566864507,
 0.0781166566864507,
 0.07792865001991967,
 0.07792865001991967,
 0.07792865001991967,
 0.07792865001991967,
 0.07792865001991967,
 0.07792865001991967,
 0.07792865001991967,
 0.07792865001991967,
 0.07792865001991967,
 0.07792865001991967,
 0.07755667343294813,
 0.07755667343294813,
 0.0770085628656519,
 0.07694837640638656,
 0.07694837640638656,
 0.07694837640638656,
 0.07694837640638656,
 0.07694837640638656,
 0.07694837640638656,
 0.07694837640638656,
 0.07694837640638656,
 0.07694837640638656,
 0.07694837640638656,
 0.07694837640638656,
 0.07647191129018727,
 0.07647191129018727,
 0.07647191129018727,
 0.07647191129018727,
 0.07647191129018727,
 0.07647191129018727,
 0.07647191129018727,
 0.07647191129018727,
 0.07647191129018727,
 0.07647191129018727,
 0.076004188790721,
 0.076004188790721,
 0.076004188790721,
 0.076004188790721,
 0.076004188790721,
 0.076004188790721,
 0.076004188790721,
 0.076004188790721,
 0.076004188790721,
 0.076004188790721,
 0.07594632491572426,
 0.07543142864047142,
 0.07530940414109724,
 0.07509392614826384,
 0.07509392614826384,
 0.07509392614826384,
 0.07509392614826384,
 0.07509392614826384,
 0.07509392614826384,
 0.07509392614826384,
 0.07509392614826384,
 0.07509392614826384,
 0.07509392614826384,
 0.07509392614826384,
 0.07509392614826384,
 0.07492686492653551,
 0.07443229275647868,
 0.07443229275647868,
 0.07443229275647868,
 0.07443229275647868,
 0.07443229275647868,
 0.07443229275647868,
 0.07443229275647868,
 0.07443229275647868,
 0.07443229275647868,
 0.07443229275647868,
 0.07443229275647868,
 0.07443229275647868,
 0.07443229275647868,
 0.07443229275647868,
 0.07443229275647868,
 0.07421560439929402,
 0.07421560439929402,
 0.07421560439929402,
 0.07421560439929402,
 0.07421560439929402,
 0.07394738666465357,
 0.07394738666465357,
 0.07394738666465357,
 0.0734718358370645,
 0.0734718358370645,
 0.07336739820667779,
 0.07336739820667779,
 0.07336739820667779,
 0.07336739820667779,
 0.07336739820667779,
 0.07336739820667779,
 0.07336739820667777,
 0.07336739820667777,
 0.07336739820667777,
 0.07254762501100118,
 0.07254762501100118,
 0.07254762501100118,
 0.07254762501100118,
 0.07254762501100118,
 0.07254762501100118,
 0.07254762501100118,
 0.07254762501100118,
 0.07254762501100118,
 0.07254762501100116,
 0.07254762501100116,
 0.07254762501100116,
 0.07254762501100116,
 0.07254762501100116,
 0.07254762501100116,
 0.07254762501100116,
 0.07254762501100116,
 0.07254762501100116,
 0.07254762501100116,
 0.07254762501100116,
 0.07254762501100116,
 0.07254762501100116,
 0.07254762501100116,
 0.07254762501100116,
 0.07254762501100116,
 0.07254762501100116,
 0.07254762501100116,
 0.07254762501100116,
 0.07209840939145001,
 0.07209840939145001,
 0.07175473098524099,
 0.07175473098524099,
 0.07175473098524099,
 0.07175473098524099,
 0.07175473098524099,
 0.07175473098524099,
 0.07175473098524099,
 0.07175473098524099,
 0.07175473098524099,
 0.07175473098524099,
 0.07175473098524099,
 0.07175473098524099,
 0.07175473098524099,
 0.07098727864204515,
 0.07098727864204515,
 0.07098727864204515,
 0.07098727864204515,
 0.07098727864204515,
 0.07098727864204515,
 0.07098727864204515,
 0.07098727864204515,
 0.07098727864204515,
 0.07098727864204515,
 0.07098727864204515,
 0.07098727864204515,
 0.07079923254047887,
 0.07079923254047887,
 0.07079923254047887,
 0.07079923254047887,
 0.07079923254047887,
 0.07079923254047887,
 0.07079923254047887,
 0.07038153430777869,
 0.07038153430777869,
 0.07024393586862707,
 0.07024393586862707,
 0.07024393586862707,
 0.06952346619889824,
 0.06952346619889824,
 0.06952346619889824,
 0.06952346619889824,
 0.06952346619889824,
 0.06952346619889824,
 0.06952346619889824,
 0.06952346619889824,
 0.06952346619889824,
 0.06952346619889824,
 0.06917144638660747,
 0.06917144638660747,
 0.06917144638660747,
 0.06917144638660747,
 0.06917144638660747,
 0.06882472016116853,
 0.06882472016116853,
 0.06882472016116853,
 0.06882472016116853,
 0.06882472016116853,
 0.06882472016116853,
 0.06882472016116853,
 0.06814662756363819,
 0.06814662756363819,
 0.06814662756363819,
 0.06814662756363819,
 0.06814662756363819,
 0.06814662756363819,
 0.06814662756363819,
 0.06814662756363819,
 0.06814662756363819,
 0.06814662756363819,
 0.06814662756363819,
 0.06765100914917384,
 0.06765100914917384,
 0.06765100914917384,
 0.06765100914917384,
 0.06765100914917384,
 0.06765100914917384,
 0.06765100914917384,
 0.06765100914917384,
 0.06765100914917384,
 0.06765100914917384,
 0.06765100914917384,
 0.06765100914917384,
 0.06765100914917384,
 0.06765100914917384,
 0.06765100914917384,
 0.06765100914917384,
 0.06765100914917384,
 0.06748819059987714,
 0.06748819059987714,
 0.06748819059987714,
 0.06748819059987714,
 0.06748819059987714,
 0.06748819059987714,
 0.0672863110252489,
 0.06684847767323797,
 0.06684847767323797,
 0.06684847767323797,
 0.06684847767323797,
 0.06657426652986062,
 0.0662266178532522,
 0.0662266178532522,
 0.0662266178532522,
 0.0662266178532522,
 0.0662266178532522,
 0.0662266178532522,
 0.0662266178532522,
 0.0662266178532522,
 0.0662266178532522,
 0.0662266178532522,
 0.0662266178532522,
 0.0662266178532522,
 0.0662266178532522,
 0.0662266178532522,
 0.0662266178532522,
 0.0662266178532522,
 0.06622661785325219,
 0.06622661785325219,
 0.06622661785325219,
 0.06622661785325219,
 0.06622661785325219,
 0.06622661785325219,
 0.06622661785325219,
 0.06622661785325219,
 0.06622661785325219,
 0.06622661785325219,
 0.06578947368421054,
 0.06562179588897107,
 0.06562179588897107,
 0.06562179588897107,
 0.06562179588897107,
 0.06562179588897107,
 0.06562179588897107,
 0.06562179588897107,
 0.06554735253444621,
 0.06521546507260247,
 0.065033247714309,
 0.065033247714309,
 0.065033247714309,
 0.065033247714309,
 0.065033247714309,
 0.06488856845230502,
 0.06488856845230502,
 0.06488856845230502,
 0.06488856845230502,
 0.06488856845230502,
 0.06488856845230502,
 0.06488856845230502,
 0.06488856845230502,
 0.06488856845230502,
 0.06488856845230502,
 0.06488856845230502,
 0.06488856845230502,
 0.06488856845230502,
 0.06488856845230502,
 0.06488856845230502,
 0.06488856845230502,
 0.06488856845230502,
 0.06488856845230502,
 0.06488856845230502,
 0.06488856845230502,
 0.06488856845230502,
 0.06446025638903101,
 0.06446025638903101,
 0.06446025638903101,
 0.06446025638903101,
 0.06446025638903101,
 0.06424925662032356,
 0.06390214842634574,
 0.06390214842634574,
 0.06390214842634574,
 0.06390214842634574,
 0.06390214842634574,
 0.06390214842634574,
 0.06362847629757779,
 0.06362847629757779,
 0.06362847629757779,
 0.06362847629757779,
 0.06362847629757779,
 0.06362847629757779,
 0.06362847629757779,
 0.06362847629757779,
 0.06362847629757779,
 0.06362847629757779,
 0.06362847629757779,

In [594]:
# protect to loss there index we can use        "enumerate" function
sorted(list(enumerate(similarity[0])), reverse=True, key=lambda x : x[1])[1:6]

[(1214, 0.28676966733820225),
 (2405, 0.26901379342448517),
 (3728, 0.2605130246476754),
 (507, 0.255608593705383),
 (539, 0.2503866978335957)]

In [595]:
def recommend(movie):
    movie_index = new_df[new_df["title"] == movie].index[0]
    distance = similarity[movie_index]
    movie_list = sorted(list(enumerate(distance)), reverse=True, key=lambda x : x[1])[1:6]

    for i in movie_list:
        # print("id => ",i[0], "title => ",new_df.iloc[i[0]].title)
        print(new_df.iloc[i[0]].title)

In [596]:
recommend("Avatar")

Aliens vs Predator: Requiem
Aliens
Falcon Rising
Independence Day
Titan A.E.

In [597]:
new_df.iloc[1216].title

'Autumn in New York'